services:
  dwar_bot:
    build: .
    container_name: dwar_bot
    env_file:
      - .env
    environment:
      DWAR_COOKIES_FILE: /app/auth/cookies.json
      DWAR_LOG_FILE: /app/bot.log
      DWAR_HEADLESS: "true"
      DWAR_LOG_CONSOLE: "true"
    volumes:
      - ./auth/cookies.json:/app/auth/cookies.json
      - ./bot.log:/app/bot.log
      - ./captchas:/app/captchas
    restart: unless-stopped
    shm_size: "256mb"
    stop_grace_period: 40s
