"""
Callback-токены Premium UI + FPC parity.
"""

# Навигация
HOME = "sc:main"
SETTINGS = "sc:settings_menu"
BACK = "sc:back"
REFRESH = "sc:refresh"
MAIN = HOME
MAIN2 = "sc:2"

# Категории настроек
CATEGORY = "sc:cat:"
SWITCH = "sc:sw:"

# Плагины (FPC-style)
PLUGINS = "sc:plugins"
PLUGIN_TOGGLE = "sc:plug:"
PLUGIN_VIEW = "sc:plugview:"
PLUGIN_ACTIVATE = "sc:plugactv:"
PLUGIN_COMMANDS = "sc:plugcmds:"
PLUGIN_CMD_RUN = "sc:plugcmdrun:"
PLUGIN_PANEL = "sc:plugpanel:"
PLUGIN_PANEL_ACT = "sc:plugpact:"
PLUGIN_DELETE = "sc:plugdel:"
PLUGIN_DELETE_OK = "sc:plugdelok:"
PLUGIN_RELOAD = "sc:plugreload:"
PLUGIN_SETTINGS = "sc:plugcfg:"
PLUGIN_SETTING = "sc:plugset:"
PLUGIN_SCHEMA_ACT = "sc:psact:"
PLUGIN_RESET = "sc:plugrst:"
PLUGIN_PIN = "sc:plugpin:"
PLUGIN_EDIT = "sc:plugedit:"
PLUGIN_SELECT_MENU = "sc:plugsell:"
PLUGIN_SELECT_SET = "sc:plugsels:"
EDIT_PLUGIN = "sc:editplug:"
PLUGIN_PAGE = "sc:plugpage:"
PLUGIN_UPLOAD = "sc:plugupload"

# Пагинация
PAGE_PREV = "sc:page:prev:"
PAGE_NEXT = "sc:page:next:"

# Автоответчик
AR_LIST = "sc:ar"
AR_ADD = "sc:aradd"
AR_DEL = "sc:ardel:"
AR_TOGGLE = "sc:art:"
AR_NOTIFY = "sc:arnot:"
AR_EDIT = "sc:aredit:"
AR_PAGE = "sc:arpage:"

# Уведомления
NOTIFY = "sc:notify:"
NOTIFY_ALL_ON = "sc:notifyall:1"
NOTIFY_ALL_OFF = "sc:notifyall:0"

# Прочее
STATUS = "sc:status"
PROFILE = "sc:profile"
PROFILE_DETAIL = "sc:profile:detail"
PARSER = "sc:parser"
PARSER_SMM = "sc:parser:smm"
PARSER_REG = "sc:parser:reg"
PARSER_AD_ON = "sc:parser:ad:1"
PARSER_AD_OFF = "sc:parser:ad:0"
PARSER_CAT = "sc:parser:cat:"
PARSER_SKIP_PRICE = "sc:parser:price:def"
BACKUP = "sc:backup"
BACKUP_DL = "sc:backup:dl"
BACKUP_UL = "sc:backup:ul"
BACKUP_EXPORT = "sc:backup:export"
HELP = "sc:help"
GEMINI = "sc:gemini"
SETUP = "sc:setup"
TMPLT_LIST = "sc:tmpl"
TMPLT_USE = "sc:tmplu:"
REPLY_CHAT = "sc:reply:"
REFUND_ORDER = "sc:refund:"
REFUND_OK = "sc:refundok:"
BL_LIST = "sc:bl"
CHECK_AUTH = "sc:check_auth"
CHECK_GEMINI = "sc:check_gemini"
SET_SESSION = "sc:set_session"
SET_GEMINI = "sc:set_gemini"
EDIT_WELCOME = "sc:edit_welcome"
EDIT_BUMP = "sc:edit_bump"
EDIT_DELIVERY = "sc:edit_delivery"
